### ISSUE TITLE
Cannot 'make' on MacOS

### ISSUE THREAD

**Issue by Thomsch** [TellinaTool/tellina_user_experiment#17]
The `make` build system to generate the experiment's zip has a conflict with the time format on MacOS for `touch`:

```
ln -s client_side experiment
cp -r client_side/.infrastructure/file_system client_side/file_system
find client_side/file_system -type f -exec chmod a+w {} \;
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
find "client_side/file_system/css/" -type f -exec touch -m {} \;
touch -m -t  client_side/file_system/css/bootstrap3/bootstrap-glyphicons.css
touch: out of range or illegal time specification: [[CC]YY]MMDDhhmm[.SS]
make: *** [TASK_G_TIME] Error 1
```

I confirm that `make` works on a Linux VM. For now, I'm updating the requirements on the root README.md

**Comment by anhnamtran** [comment]
Is there a PR for this change yet? 

I think requiring Linux is perfectly acceptable, as most CSE students should have some access to Linux.

**Comment by mernst** [comment]
From the script output, the first problem seems to be with the `find` command, because there is a "usage:" message after the first `find` command.  There might also be a problem with `touch`.

**Comment by Thomsch** [comment]
@anhnamtran This bug affects developers on MacOS when compiling the package for the participants. The participants are required to use a Linux VM as you pointed out.

@mernst Thank you for pointing out the problem with `find`. I will also investigate.

There is no PR for this change yet. I will take care of it last since it's non-blocking and only affects my comfort.

**Comment by anhnamtran** [comment]
@Thomsch Ah okay my bad, for some reason I didn't make the association that Mac dev is affected.

The `find` is actually fine I believe, the usage message is for `date`, can you verify the version of the `date` command on Linux and on MacOS? `date --version` should work. 

The offending line is likely:
https://github.com/TellinaTool/tellina_user_experiment/blob/782d6857dd2a5e95fb38543c29899b68d5355664/Makefile#L67

This line executes fine and it's after the line mentioned above
https://github.com/TellinaTool/tellina_user_experiment/blob/782d6857dd2a5e95fb38543c29899b68d5355664/Makefile#L70

Which then leads to 
https://github.com/TellinaTool/tellina_user_experiment/blob/782d6857dd2a5e95fb38543c29899b68d5355664/Makefile#L72

Which outputs the `touch` error.

**Comment by Thomsch** [comment]
Thank you for the breakdown!

Linux VM date: `date (GNU coreutils) 8.30`
MacOS date: Apparently `date` is a BSD command on MacOS. To get the GNU `date` command, I need to use `gdate` T_T.

I'll see if there is either a common format that works for both. Otherwise, I'll have to check the OS and use an alias for the command.

**Comment by anhnamtran** [comment]
Can you try replacing `shell date` with `bash -c date`, or even just `sh -c date`, that should in theory force the GNU version. If that doesn't work, it might be worth it to just symlink `gdate` as `date` for your own convenience. 

Either way, it might be useful to have a check to make sure the system is using GNU `date` instead of some other symlink/binary.

**Comment by Thomsch** [comment]
Thank! Will try that. I have to run to class.

**Comment by Thomsch** [comment]
`bash -c date` works on MacOs but causes the command to fail on Linux 🤦.

After discussing with Mike, we realized that this task won't be used anyway for the user experiment since we resampled them.
