### ISSUE TITLE
`log.csv` Loses Write Permissions Due To CSE Homes Configurations

### ISSUE THREAD

**Issue by anhnamtran** [TellinaTool/tellina_user_experiment#4]
The POST handler is currently being hosted on CSE Homes and is writing to the `log.csv` file located under `/cse/web/homes/atran35/tellina_user_experiment/server_side/log.csv`.

The permissions of this folder is `644` or `rw-r--r--`. This prevents the POST handler from writing to the file. The POST handler itself also does not return an error when the write fails. This leads to "silent" failures where the client side is sending write log requests that are not being stored into the log file.

A workaround for this issue is to manually set the permissions of `log.csv` to `666` or `rw-rw-rw`. However, the permissions gets reset to `644` on a Git `pull`, `stash`, or `merge`.

Another is to prevent Git from tracking `log.csv`. 

The desired outcome is for `log.csv` have read-write permissions for all without having to manually set it every time a Git update is performed.

**Comment by mernst** [comment]
Why is log.csv under Git control?

A fix is to add a git hook to set the permissions.  `post-merge` might be the right hook to use.

**Comment by anhnamtran** [comment]
`log.csv` is under Git control could allow for a simpler backup procedures, where we can periodically commit the file to "back it up". Git will then handle the history as well as recovery for us.

I will take a look at git hooks.

**Comment by mernst** [comment]
This repository is public.  That means that the usernames and performance is publicly available in a non-anonymized way.  We don't want that.

**Comment by anhnamtran** [comment]
Right. I will remove Git tracking for `log.csv`.

**Comment by anhnamtran** [comment]
Closed by ccc8c8d52aeb027147ccb40e5e3c70445ba22c36
