### ISSUE TITLE
State of branch `website`

### ISSUE THREAD

**Issue by Thomsch** [TellinaTool/tellina_user_experiment#9]
We're in the process of conducting a new user experiment. 
I was wondering if the branch `website` is ready to be merged or, if not, what is the work left on it.  What is the purpose of this branch?

@anhnamtran @mernst

**Comment by anhnamtran** [comment]
This branch might have been deprecated. I don't particularly remember why. You might want to double check that none of the content in that branch is particularly important. Sorry about the ambiguity of this.

**Comment by Thomsch** [comment]
It seems that commit 62fce776fca0f3802f4e6dccc77e37171ccacf7a contains some of the changes present in branch `website`. However, there is no traces of the root folder `website` introduced in the branch in the former commit. Would it be possible that the changes go implemented instead in client_side or server_side?

**Comment by anhnamtran** [comment]
Okay, I believe that the branch should be safe to delete. The `website` directory contains a deprecated "training" page that is no longer needed, as IIRC the training is now part of `client_side`. Correct me on this if I'm wrong.

**Comment by Thomsch** [comment]
Yes, that seems to be the case. Great! Thank you for the help.
